name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
    - uses: actions/upload-artifact@v4
      with:
        name: RF-Bot
        path: bin/Release/net8.0-windows/win-x64/publish/
